name: remla-app-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - Flask==2.3.2
    - requests==2.31.0
    - python-dotenv==1.0.0
    - flasgger==0.9.7.1
    - prometheus-flask-exporter==0.23.2
    - prometheus-client==0.22.0
    - git+https://github.com/remla25-team8/lib-version.git@v0.1.10
